import { useState } from 'react'
import { Sparkles, BookMarked, CheckCircle2, FlaskConical, Dna } from 'lucide-react'
import {
  wasteStats,
  gradeForScore,
  getUnits,
  WASTE_STANDARDS,
  type WasteStream,
  type Severity,
} from '../data'
import { ScoreRing, Pill } from '../components/ui'

const SEV_ORDER: Record<Severity, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
  OK: 4,
}

function RecommendationCard({ w }: { w: WasteStream }) {
  const tone =
    w.ai.verdict === 'Improperly handled'
      ? 'high'
      : w.ai.verdict === 'Needs improvement'
        ? 'med'
        : 'low'
  return (
    <div className="finding" style={{ alignItems: 'flex-start' }}>
      <span className={`sev-tag ${w.ai.severity.toLowerCase()}`}>{w.ai.severity}</span>
      <div className="grow">
        <div className="flex items-center gap-2" style={{ marginBottom: 3 }}>
          {w.category === 'Chemical' ? (
            <FlaskConical size={14} color="var(--high)" />
          ) : (
            <Dna size={14} color="var(--info)" />
          )}
          <span className="f-title" style={{ margin: 0 }}>
            {w.name}
          </span>
          <Pill tone={tone}>{w.ai.verdict}</Pill>
        </div>
        <div className="muted" style={{ fontSize: 11.5, marginBottom: 6 }}>
          Generated by: {w.sourceActivity} · Currently: {w.disposalActivity}
        </div>
        <div className="f-rec">{w.ai.summary}</div>
        <div className="ai-rec-actions" style={{ margin: '8px 0' }}>
          {w.ai.actions.map((a, i) => (
            <div className="ai-rec-action" key={i}>
              <CheckCircle2 size={13} color="var(--accent)" />
              <span>{a}</span>
            </div>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          {w.ai.standards.map((s) => (
            <span className="f-ref" key={s} style={{ background: 'var(--info-tint)', padding: '2px 7px', borderRadius: 6 }}>
              {s}
            </span>
          ))}
        </div>
      </div>
    </div>
  )
}

export default function Assessment() {
  const units = getUnits().filter((u) => wasteStats.streamsByUnit(u.id).length > 0)
  const [activeId, setActiveId] = useState(units[0]?.id ?? '')
  const active = units.find((u) => u.id === activeId) ?? units[0]

  const streams = wasteStats
    .streamsByUnit(active.id)
    .slice()
    .sort((a, b) => SEV_ORDER[a.ai.severity] - SEV_ORDER[b.ai.severity])
  const score = wasteStats.unitScore(active.id) ?? 0
  const grade = gradeForScore(score)

  return (
    <div className="row" style={{ alignItems: 'flex-start' }}>
      {/* Unit picker */}
      <div style={{ flexBasis: '30%', flexShrink: 0, minWidth: 240 }}>
        <div className="section-title">Units generating waste</div>
        {units.map((u) => {
          const s = wasteStats.unitScore(u.id) ?? 0
          const g = gradeForScore(s)
          return (
            <button
              key={u.id}
              className={`lab-pick ${u.id === activeId ? 'active' : ''}`}
              onClick={() => setActiveId(u.id)}
            >
              <div>
                <div className="lp-name">{u.short}</div>
                <div className="lp-unit">
                  {wasteStats.streamsByUnit(u.id).length} streams
                </div>
              </div>
              <div className="lp-score" style={{ color: `var(--${g.tone})` }}>
                {s}
              </div>
            </button>
          )
        })}

        {/* Standards catalog */}
        <div className="card" style={{ marginTop: 14 }}>
          <div className="card-head">
            <h3 style={{ fontSize: 13, display: 'flex', alignItems: 'center', gap: 6 }}>
              <BookMarked size={14} /> Standards applied
            </h3>
          </div>
          <div className="card-pad" style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
            {WASTE_STANDARDS.map((s) => (
              <div key={s.code} style={{ fontSize: 11.5 }}>
                <div style={{ fontWeight: 700 }}>{s.code}</div>
                <div className="muted">{s.title}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Report */}
      <div className="grow stack" style={{ flexBasis: '70%' }}>
        <div className="card">
          <div className="card-pad" style={{ display: 'flex', gap: 24, alignItems: 'center', flexWrap: 'wrap' }}>
            <ScoreRing score={score} />
            <div className="grow" style={{ minWidth: 220 }}>
              <div className="flex items-center gap-2" style={{ marginBottom: 6 }}>
                <Sparkles size={18} color="var(--gold)" />
                <h2 style={{ fontSize: 18 }}>{active.short}</h2>
              </div>
              <div className="muted" style={{ marginBottom: 12 }}>
                {active.building} · AI waste-handling assessment
              </div>
              <Pill tone={grade.tone}>{grade.label}</Pill>
              <div className="flex gap-3" style={{ marginTop: 14, flexWrap: 'wrap' }}>
                <span className="tag">
                  <CheckCircle2 size={12} color="var(--low)" /> {streams.filter((w) => w.status === 'Compliant').length} proper
                </span>
                <span className="tag">
                  {streams.filter((w) => w.status === 'Partially compliant').length} need improvement
                </span>
                <span className="tag">
                  {streams.filter((w) => w.status === 'Non-compliant').length} improper
                </span>
              </div>
            </div>
          </div>
        </div>

        <div className="card">
          <div className="card-head">
            <h3>Per-stream recommendations</h3>
            <span className="sub">{streams.length} waste streams · sorted by priority</span>
          </div>
          <div className="card-pad" style={{ paddingTop: 4 }}>
            {streams.map((w) => (
              <RecommendationCard w={w} key={w.id} />
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
