import { Printer, Send } from 'lucide-react'
import { wasteStats, gradeForScore } from '../data'
import { Pill, statusTone } from '../components/ui'
import { useToast } from '../components/Toast'
import { useApp } from '../store/app'

export default function ConsolidatedReport() {
  const { toast } = useToast()
  const { units: UNITS } = useApp()

  const generatingUnits = UNITS.filter((u) => wasteStats.streamsByUnit(u.id).length > 0)
  const campusScore = wasteStats.campusHandlingScore
  const chemCount = wasteStats.countByCategory('Chemical')
  const bioCount = wasteStats.countByCategory('Biological')

  const today = new Date('2026-07-08').toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <div className="stack">
      {/* Action bar */}
      <div className="flex items-center justify-between wrap gap-3 no-print">
        <span className="count-note">
          Draft generated from live registry data · {today}
        </span>
        <div className="flex gap-2">
          <button className="btn btn-ghost" onClick={() => window.print()}>
            <Printer size={15} /> Export / Print
          </button>
          <button
            className="btn btn-primary"
            onClick={() =>
              toast('Report submitted to the Office of the President.', 'success')
            }
          >
            <Send size={15} /> Submit to Office of the President
          </button>
        </div>
      </div>

      {/* Paper */}
      <div className="paper">
        <div className="rpt-head">
          <div className="org">VISAYAS STATE UNIVERSITY</div>
          <div className="sub">Baybay City, Leyte · Office of the University Safety Officer</div>
          <div className="sub">
            Technical Working Group on Hazardous Laboratory Materials
          </div>
        </div>

        <h2 className="rpt-title">
          Consolidated Report on Hazardous Laboratory Waste &amp; Disposal
        </h2>
        <div className="rpt-meta">
          Submitted to the Office of the President · Reporting period: Q2 2026 (Apr–Jun)
          <br />
          Prepared by the TWG · {today}
        </div>

        {/* I. Executive Summary */}
        <h3 className="rpt-sec">I. Executive Summary</h3>
        <p className="rpt-body">
          Pursuant to the university mandate on the survey and profiling of hazardous
          laboratory wastes, the Technical Working Group (TWG) documented the chemical and
          biological waste streams generated by {generatingUnits.length} academic units and
          the activities each unit uses to dispose of them. A total of{' '}
          <b>{wasteStats.total} waste streams</b> are tracked university-wide —{' '}
          {chemCount} chemical and {bioCount} biological.
        </p>
        <p className="rpt-body">
          Each stream's disposal activity was evaluated by AI against international and
          national biosafety and chemical-safety standards (WHO Laboratory Biosafety Manual,
          CDC/NIH BMBL, WHO/DOH health-care-waste guidance, OSHA, US EPA RCRA, NFPA, and
          Philippine RA 6969 / 9275 / 8749 and DENR DAO 2013-22). The assessment found{' '}
          <b>{wasteStats.proper} streams properly handled</b>,{' '}
          <b>{wasteStats.needsImprovement} needing improvement</b>, and{' '}
          <b>{wasteStats.improper} improperly handled</b>. The campus-wide waste-handling
          score is <b>{campusScore}/100</b> ({gradeForScore(campusScore).label}), with{' '}
          {wasteStats.openRecommendations} AI recommendations open for action.
        </p>

        {/* II. Waste Generation & Disposal by Unit */}
        <h3 className="rpt-sec">II. Waste Generation &amp; Disposal by Unit</h3>
        <div className="table-wrap">
          <table className="data" style={{ fontSize: 12.5 }}>
            <thead>
              <tr>
                <th>Academic unit</th>
                <th>Streams</th>
                <th>Chem / Bio</th>
                <th>Handling score</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {UNITS.map((u) => {
                const streams = wasteStats.streamsByUnit(u.id)
                const score = wasteStats.unitScore(u.id)
                const worst = wasteStats.unitWorstSeverity(u.id)
                const label =
                  streams.length === 0
                    ? 'No streams'
                    : worst === 'OK'
                      ? 'On track'
                      : `${worst} priority`
                const tone =
                  streams.length === 0
                    ? 'neutral'
                    : worst === 'CRITICAL' || worst === 'HIGH'
                      ? 'high'
                      : worst === 'MEDIUM'
                        ? 'med'
                        : 'low'
                return (
                  <tr key={u.id}>
                    <td className="cell-main">{u.name}</td>
                    <td className="mono">{streams.length}</td>
                    <td className="mono">
                      {streams.filter((w) => w.category === 'Chemical').length} /{' '}
                      {streams.filter((w) => w.category === 'Biological').length}
                    </td>
                    <td className="mono">{score !== null ? `${score}/100` : '—'}</td>
                    <td>
                      <Pill tone={tone as 'high' | 'med' | 'low' | 'neutral'}>{label}</Pill>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>

        {/* III. Key Findings & Recommendations */}
        <h3 className="rpt-sec">III. Key Waste-Handling Findings &amp; Recommendations</h3>
        <ol className="rpt-list">
          <li>
            <b>Formalin poured to drain (Veterinary Medicine).</b> Spent formaldehyde
            fixative is discharged to the sink. As a Group-1 carcinogen this must be
            collected and neutralized/recovered or hauled — never drained (OSHA 1910.1048,
            RA 9275, DENR DAO 2013-22).
          </li>
          <li>
            <b>Heavy-metal digestates mixed with general acid waste (Agri-Chem).</b> Metal
            digestates must be collected as a separate toxicity-characteristic stream and
            consigned to a DENR-accredited hauler; no sewer discharge (RCRA D004–D011, RA
            6969, RA 9275).
          </li>
          <li>
            <b>Oxidizer waste stored beside flammables (Agri-Chem).</b> Segregate peroxide
            waste from solvents and stop routine drain disposal of concentrated oxidizer
            (UN GHS Rev.10, NFPA 430).
          </li>
          <li>
            <b>Bloodborne sharps overfilled &amp; unrestricted (Biological Sciences).</b>{' '}
            Seal sharps containers at ≤¾ full, restrict handling to HBV-vaccinated staff,
            and treat before disposal (OSHA 1910.1030, WHO/DOH health-care-waste guidance).
          </li>
          <li>
            <b>BSL-3 autoclave validation lapsed (Veterinary Medicine).</b> Resume monthly
            biological-indicator (spore-test) validation and quarantine treated{' '}
            <i>M. tuberculosis</i> waste until a passing cycle is documented (WHO Biosafety
            Manual, CDC/NIH BMBL, ISO 11138).
          </li>
        </ol>

        {/* Signatures */}
        <div className="sign-block">
          <div className="sig">
            <div className="line">Dr. R. Salazar</div>
            <div className="role">TWG Chair · University Safety Officer</div>
          </div>
          <div className="sig">
            <div className="line">Office of the President</div>
            <div className="role">Noted &amp; Approved</div>
          </div>
        </div>
      </div>
    </div>
  )
}
