import { useState } from 'react'
import {
  Recycle,
  AlertOctagon,
  CheckCircle2,
  FlaskConical,
  Dna,
  ChevronDown,
  Sparkles,
  ArrowRight,
  Factory,
  Trash2,
} from 'lucide-react'
import { wasteStats, type WasteStream, type Severity } from '../data'
import { KpiCard, Pill, statusTone } from '../components/ui'
import { useApp } from '../store/app'

type CatFilter = 'All' | 'Chemical' | 'Biological'

const sevClass = (s: Severity) => s.toLowerCase()

function StreamRow({ w }: { w: WasteStream }) {
  const [open, setOpen] = useState(false)
  return (
    <div className={`waste-card ${w.status === 'Non-compliant' ? 'flag' : ''}`}>
      <button className="waste-card-head" onClick={() => setOpen((o) => !o)} aria-expanded={open}>
        <span className={`waste-cat-icon ${w.category === 'Chemical' ? 'chem' : 'bio'}`}>
          {w.category === 'Chemical' ? <FlaskConical size={16} /> : <Dna size={16} />}
        </span>
        <div className="grow" style={{ minWidth: 0 }}>
          <div className="cell-main">{w.name}</div>
          <div className="cell-sub">
            {w.hazardClass} · <span className="mono">{w.hazardCode}</span> · {w.volumePerMonth}
          </div>
        </div>
        <Pill tone={statusTone(w.status)}>{w.status}</Pill>
        <ChevronDown
          size={17}
          color="var(--muted)"
          style={{ transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.15s' }}
        />
      </button>

      {/* generation → disposal summary (always visible) */}
      <div className="waste-flow">
        <div className="waste-flow-step">
          <span className="wf-label">
            <Factory size={12} /> Generating activity
          </span>
          <span className="wf-val">{w.sourceActivity}</span>
        </div>
        <ArrowRight size={16} className="wf-arrow" />
        <div className="waste-flow-step">
          <span className="wf-label">
            <Trash2 size={12} /> Current disposal activity
          </span>
          <span className="wf-val">{w.disposalActivity}</span>
        </div>
      </div>

      {open && (
        <div className="waste-detail">
          <div className="waste-meta-grid">
            <div>
              <span className="wm-k">Interim storage</span>
              <span className="wm-v">{w.storage}</span>
            </div>
            <div>
              <span className="wm-k">Disposal method</span>
              <span className="wm-v">{w.method}</span>
            </div>
            <div>
              <span className="wm-k">Treatment</span>
              <span className="wm-v">{w.treatment}</span>
            </div>
            <div>
              <span className="wm-k">Hauler</span>
              <span className="wm-v">{w.hauler ?? '— none assigned —'}</span>
            </div>
            <div>
              <span className="wm-k">Manifest</span>
              <span className="wm-v mono">{w.manifest ?? '—'}</span>
            </div>
          </div>

          {/* AI recommendation */}
          <div className="ai-rec">
            <div className="ai-rec-head">
              <Sparkles size={15} color="var(--gold)" />
              <b>AI recommendation</b>
              <span className={`sev-tag ${sevClass(w.ai.severity)}`} style={{ marginLeft: 'auto' }}>
                {w.ai.verdict}
              </span>
            </div>
            <p className="ai-rec-summary">{w.ai.summary}</p>
            <div className="ai-rec-actions">
              {w.ai.actions.map((a, i) => (
                <div className="ai-rec-action" key={i}>
                  <CheckCircle2 size={13} color="var(--accent)" />
                  <span>{a}</span>
                </div>
              ))}
            </div>
            <div className="ai-rec-standards">
              <span className="wm-k">Based on</span>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 4 }}>
                {w.ai.standards.map((s) => (
                  <span className="tag" key={s} style={{ borderColor: 'rgba(42,111,219,0.25)', color: 'var(--info)' }}>
                    {s}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default function WasteRegister() {
  const [cat, setCat] = useState<CatFilter>('All')
  const { units: allUnits, wasteStreams } = useApp()
  const units = allUnits.filter((u) => wasteStreams.some((w) => w.unitId === u.id))

  return (
    <div className="stack">
      <div className="card card-pad">
        <p className="muted" style={{ fontSize: 13, maxWidth: 820 }}>
          Chemical and biological wastes generated by each academic unit, the activities
          that produce them, and how the unit currently disposes of them. Each stream is
          evaluated by AI against <b style={{ color: 'var(--text)' }}>DENR DAO 2013-22, RA 6969 / 9275 / 8749,
          US EPA RCRA, OSHA, NFPA, WHO Biosafety, CDC/NIH BMBL, DOH and Basel</b> standards.
        </p>
      </div>

      <div className="grid grid-4">
        <KpiCard icon={<Recycle size={18} />} value={wasteStats.total} label="Waste streams tracked" tone="info" />
        <KpiCard icon={<CheckCircle2 size={18} />} value={wasteStats.proper} label="Properly handled" tone="low" />
        <KpiCard icon={<Sparkles size={18} />} value={wasteStats.needsImprovement} label="Needs improvement" tone="med" />
        <KpiCard icon={<AlertOctagon size={18} />} value={wasteStats.improper} label="Improperly handled" tone="high" />
      </div>

      <div className="filter-row">
        {(['All', 'Chemical', 'Biological'] as const).map((c) => (
          <button key={c} className={`filter-pill ${cat === c ? 'active' : ''}`} onClick={() => setCat(c)}>
            {c}
            <span className="mono" style={{ opacity: 0.7 }}>
              {c === 'All' ? wasteStats.total : wasteStats.countByCategory(c)}
            </span>
          </button>
        ))}
      </div>

      {/* Grouped by unit */}
      {units.map((u) => {
        const streams = wasteStreams.filter(
          (w) => w.unitId === u.id && (cat === 'All' || w.category === cat),
        )
        if (streams.length === 0) return null
        const score = wasteStats.unitScore(u.id)
        return (
          <div className="card" key={u.id}>
            <div className="card-head">
              <h3 style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                {u.short}
                <span className="sub" style={{ fontWeight: 400 }}>· {u.building}</span>
              </h3>
              <span className="sub">
                {streams.length} stream{streams.length > 1 ? 's' : ''}
                {score !== null && <> · handling score <b className="mono">{score}</b></>}
              </span>
            </div>
            <div className="card-pad" style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {streams.map((w) => (
                <StreamRow w={w} key={w.id} />
              ))}
            </div>
          </div>
        )
      })}
    </div>
  )
}
